### ISSUE TITLE
Can't get it running

### ISSUE THREAD

**Issue by gligoran** [darrencauthon/MvcTurbine.GoogleSiteMap#1]
Hi!

I can't get sitemaps up and running. MvcTurbine just won't run the IRouteRegistrator and IServiceRegistration in the MvcTurbine.GoogleSiteMap assembly. I even tried getting the source code, adding the MvcTurbine.GoogleSiteMap project to my solution and setting breakpoints to see if it hits, but it doesn't. The IRouteRegistrator and IServiceRegistration implementation in my project work fine.
Is there something I'm doing wrong? How to I set up MvcTurbine or MvcTurbine.GoogleSiteMap so I can just add the assembly?

Thanks,
Goran

**Comment by darrencauthon** [comment]
Are you using version 3.2 of MVCTurbine?  

There was an update to MvcTurbine that inadvertently broke some of my MvcTurbine plugins, including MvcTurbine.GoogleSiteMap.  Since I started the name of my assembly with "MvcTurbine.", MVC Turbine thinks I'm part of the core system and is preventing the blades from spinning up.  A link to the fix is below, and it will be included in the next version of MVC Turbine.  

One solution for you will be to recompile MvcTurbine to the latest version, to get the fix.  Or if you drop to MvcTurbine 3.1 or 3.0 it will work.  And I'll tell you what:  Tonight I'll see what I can do to get this fixed.  I'm juggling some work stuff and I have a 6-week-old baby, so I may not be able to get it fixed completely.

I'm very sorry for the trouble!  

http://bit.ly/iEHqGu

**Comment by gligoran** [comment]
Thanks for the very quick response Darren.

I managed to get i running now with the latest MvcTurbine from GitHub. Thanks.
Oh, and congratulations on the baby. There's no need to hurry on the fix, just please notify me when the new MvcTurbine goes up, so I can get it from NuGet, as I had to remove all the MvcTurbine NuGet packages because of the dependencies.

Bye,
Goran

**Comment by gligoran** [comment]
Hi!

Thanks for the updated MvcTurbine 3.2.1. Now it works great with MvcTurbine.GoogleSiteMap.

Bye,
Goran
